Remove Helm 2 support, add integration tests
deviceinsight/helm-maven-plugin pull request #189
Opened 2023-03-22 11:53 UTC by mwalser

This is the start of a series of changes for an upcoming major release of the helm-maven-plugin.

As first PR, the support for Helm 2 is removed, unused dependencies are removed from the pom.xml and integration tests are added.

2023-03-22 14:30 UTC, hho requested changes
Nothing major, only some cleanups

2023-03-22 14:30 UTC, hho commented on src/test/it/package-lint-template/verify.groovy
> +assert logLines.any { line -> line.contains("1 chart(s) linted, 0 chart(s) failed") }
```suggestion
// Package goal
assert logLines.any { it.contains("Successfully packaged chart and saved it to") }

// Lint goal
assert logLines.any { it.contains("Chart.yaml: icon is recommended") }
assert logLines.any { it.contains("1 chart(s) linted, 0 chart(s) failed") }
```

2023-03-22 14:30 UTC, hho commented on src/main/kotlin/com/deviceinsight/helm/ResolveHelmMojo.kt
> +		val (majorVersion, minorVersion) = helmVersion.split('.').map(String::toInt)
Maybe add a sanity check (i.e. check that the format actually matches `\d+(\.\d+){2}`)?

2023-03-22 14:30 UTC, hho commented on pom.xml
>  		<maven.version>3.6.2</maven.version>
Maybe we should update to 3.9.1? (3.9 includes the update to JDK 8 as a baseline)

2023-03-22 14:30 UTC, hho commented on pom.xml
> +		<maven-invoker-plugin.groovy.version>4.0.6</maven-invoker-plugin.groovy.version>
Let's not add dependencies already out of date…
```suggestion
		<maven-invoker-plugin.version>3.5.0</maven-invoker-plugin.version>
		<maven-invoker-plugin.groovy.version>4.0.10</maven-invoker-plugin.groovy.version>
```

2023-03-22 14:30 UTC, hho commented on pom.xml
> +					<postBuildHookScript>verify.groovy</postBuildHookScript>
Any chance to do the tests in Kotlin instead? (e.g. Kotlin Scripting)

Or is this some hardcoded thing in the invoker plugin?

2023-03-24 09:16 UTC, mwalser reviewed
@hho Thanks for the review, I applied your suggestions and also added a default value for Helm version

2023-03-24 09:28 UTC, hho commented on pom.xml
>  		<maven.version>3.6.2</maven.version>
Given that the warning also appears on use of the current plugin with the new Maven, I think we'll have to address it at some point.
But OK, it doesn't have to be in this PR.

2023-03-24 09:28 UTC, hho approved these changes

2023-03-24 11:46 UTC, merged