Add HTTP status code 200 to allowed return codes
deviceinsight/helm-maven-plugin pull request #60
Opened 2020-09-15 11:40 UTC by Chleij

When using PUT to upload an artifact to a Sonatype Nexus OSS repository a HTTP status code 200 may be returned. Please add status code 200 to the list of allowed status codes to enable work with Sonytype Nexus.

2020-09-15 12:17 UTC, pvorb requested changes

2020-09-15 12:17 UTC, pvorb commented on src/main/kotlin/com/deviceinsight/helm/DeployMojo.kt
> +				if ( (statusCode != 200) || (statusCode != 201) ) {
I'd suggest to accept any response status code in the 2xx range.

```suggestion
				if (statusCode >= 200 && statusCode < 300) {
```

2020-09-15 12:38 UTC, Chleij reviewed
Looks good to me. Changed code accordingly.

2020-09-15 12:42 UTC, pvorb approved these changes

2020-09-15 12:46 UTC, merged

2020-11-03 13:28 UTC, pvorb commented
I've just released 2.7.0 including your fix. It should be available on Maven Central in a few minutes. Sorry for the delay.